### ISSUE TITLE
Wasm SIMD unsupported 

### ISSUE THREAD

**Issue by MarketingPip** [hectorm/chafa-wasm#121]
When trying demo things fail.

Error in console is:

```
Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Wasm SIMD unsupported @+285). Build with -sASSERTIONS for more info.
    at J (chafa.js:15:102)
    at chafa.js:16:131
```

**Comment by hectorm** [comment]
What browser and operating system do you use?

**Comment by MarketingPip** [comment]
@hectorm - Windows 7. 

Chrome (unsure of version - tho older version).

**Comment by hectorm** [comment]
It seems that you are using an old browser that does not support [WASM SIMD](https://caniuse.com/wasm-simd), unfortunately the only thing I can recommend is to use a newer version. I cannot guarantee compatibility with older versions.
