### ISSUE TITLE
Support for Sixel pixel mode

### ISSUE THREAD

**Issue by TechSavage2** [hectorm/chafa-wasm#24]
Hi, thanks for this.

Would it be possible for you to implement support to configure Sixel pixel mode/output (ANSI module). This is supported in many terminal emulators (xterm, konsole, kitty etc.) and gives a close-to-bitmap look (true color/pixel level.)

It would be for this config: `ChafaPixelMode`
https://github.com/hectorm/chafa-wasm/blob/master/src/chafa.js#L324

https://github.com/hectorm/chafa-wasm/blob/master/src/chafa-bindings.hpp#L35

In any case, thanks.

**Comment by hectorm** [comment]
Better late than never, done!
